---
- name: Create /etc/apt/sources.list.d/kubernetes.list
  copy:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: '0644'
  become: yes
  register: kubernetes_list

- name: Add apt signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes

- name: Update repositories
  apt:
    update_cache: yes
  become: yes

- name: apt-get install k8s stuff
  apt:
    name:
      - kubeadm=1.18.9-00
      - kubectl=1.18.9-00
      - kubelet=1.18.9-00
    state: present
  become: True
