---
- name: Create /etc/apt/sources.list.d/kubernetes.list
  copy:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: '0644'
  become: yes
  register: kubernetes_list

- name: Add apt signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes

- name: Update repositories
  apt:
    update_cache: yes
  become: yes

- name: Install Kubernetes packages
  apt:
    name:
      - kubeadm={{ k8s_version }}
      - kubectl={{ k8s_version }}
      - kubelet={{ k8s_version }}
    state: present
  become: yes

- name: Hold Kubernetes packages at current version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  become: yes
  loop:
    - kubeadm
    - kubectl
    - kubelet
