---
- name: Disable serial console
  ansible.builtin.replace:
    path: /boot/cmdline.txt
    regexp: 'console=serial0,115200 '
    replace: ''
  become: yes

- name: Enable uart
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    line: 'enable_uart=1'
  become: yes
