---
- name: Create kubernetes config directory
  file:
    path: /root/.kube
    owner: root
    group: root
    mode: 0755
    state: directory
  become: yes

- name: Check admin.conf
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf

- name: admin.conf exists
  block:
    - name: Copy over the kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
      become: yes
  when: admin_conf.stat.exists

- name: admin.conf does not exist
  block:
    - name: Copy over the kube config
      copy:
        src: /etc/kubernetes/kubelet.conf
        dest: /root/.kube/config
        remote_src: yes
      become: yes
  when: admin_conf.stat.exists == False

- name: Set kube config permissions
  file:
    path: /root/.kube/config
    owner: root
    group: root
    mode: 0600
  become: yes
