---
- name: Update repositories
  apt:
    update_cache: yes
    upgrade: dist
  become: yes

- name: apt-get install git
  apt:
    name: git
    state: latest
  become: True

- name: hostname file
  copy:
    content: '{{hostname}}'
    dest: '{{mount_point}}/etc/hostname'
    # group: root
    # owner: root
    mode: 0644

- name: Update '{{mount_point}}/etc/hosts'
  replace:
    path: '{{mount_point}}/etc/hosts'
    regexp: 'raspberrypi'
    replace: '{{hostname}}'
