---
- name: Update repositories
  apt:
    update_cache: yes
    upgrade: dist
  become: yes

- name: apt-get install git
  apt:
    name: git
    state: latest
  become: True

- name: hostname file
  copy:
    content: '{{hostname}}'
    dest: '/etc/hostname'
    group: root
    owner: root
    mode: 0644
  become: True

- name: Update '/etc/hosts'
  replace:
    path: '/etc/hosts'
    regexp: '127.0.1.1	.*'
    replace: '127.0.1.1	{{hostname}}'
  become: True
