---
- name: "Prepare for and install K8s"
  hosts: k8sworkers k8sprimary
  roles:
    - role: raspinit
    - role: python3
    - role: locale
    - role: keyboard
    - role: k8s/initialize
    - role: k8s/install
