---
- name: "US-100 Distance Sensor"
  hosts: food
  roles:
    - role: raspinit
    - role: python3
    - role: locale
    - role: keyboard
    - role: gpio
    - role: serial
    - role: reboot
    - role: pi_server
      sensor_modules:
        - us100
