{
 "title": "Coopernetes Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Food Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rpi187_us100_distance", "legendFormat": "food" }
   ]
  },
  {
   "title": "Coopernetes Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rpi128_dht22_18_temperature", "legendFormat": "outside temp" },
    { "expr": "rpi131_dht22_18_temperature", "legendFormat": "inside temp" },
    { "expr": "rpi187_us100_temperature", "legendFormat": "house" }
   ]
  },
  {
   "title": "Coopernetes Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rpi128_dht22_18_humidity", "legendFormat": "outside humidity" },
    { "expr": "rpi131_dht22_18_humidity", "legendFormat": "inside humidity" }
   ]
  }
 ]
}