---
- name: apt-get install python-smbus
  apt:
    name: python-smbus
    state: latest
  become: True

- name: apt-get install i2c-tools
  apt:
    name: i2c-tools
    state: latest
  become: True

- name: Enable i2c
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^#dtparam=i2c_arm=on'
    line: 'dtparam=i2c_arm=on'

- name: Enable spi
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^#dtparam=spi=on'
    line: 'dtparam=spi=on'

- name: Install RPI.GPIO
  pip:
    name: RPI.GPIO
  become: True

- name: apt-get install libgpiod2
  apt:
    name: libgpiod2
    state: latest
  become: True
