---
release_branch: 1-19
release: 1
k8s_version: v1.19.6
repository_url: public.ecr.aws/h1r8a7l5
artifact_url: "https://eks-d-postsubmit-artifacts.s3-us-west-2.amazonaws.com/kubernetes-{{ release_branch }}/releases/{{ release }}/artifacts"
kubernetes_url: "{{ artifact_url }}/kubernetes/{{ k8s_version }}"
