---
- name: Check for deployemnt
  command: kubectl get deploy --namespace ingress-nginx ingress-nginx-controller
  failed_when: False
  changed_when: False
  register: deployment

- name: Start the deployment
  block:
    - name: Copy over the kube config
      copy:
        src: nginx-ingress.yaml
        dest: /home/pi/nginx-ingress.yaml

    - name: Add deployment
      command: kubectl apply -f nginx-ingress.yaml
  when: deployment.rc != 0
