---
- name: "Download image {{ download[arch].url }}/{{ download[arch].image }}"
  get_url:
    url: "{{ download[arch].url }}/{{ download[arch].image }}"
    dest: "./{{ download[arch].image }}"

#- name: Get list of mounts
#  command: diskutil list
#  register: mounts
#  become: yes
