---
- name: Get disk number for SD card
  shell: "diskutil list | grep -A 1 'external, physical' | grep '/dev/disk' | head -1 | awk '{print $1}'"
  register: sd_card_disk
  changed_when: False

- name: Unmount all partitions on SD card
  shell: "diskutil unmountDisk {{ sd_card_disk.stdout }}"
  when: sd_card_disk.stdout != ""
  become: yes

- name: "Create Downloads"
  file:
    path: ./Downloads
    state: directory
    mode: 0755

- name: "Download image {{ download[arch].url }}/{{ download[arch].image }}"
  get_url:
    url: "{{ download[arch].url }}/{{ download[arch].image }}"
    dest: "./Downloads/{{ download[arch].image }}"

- name: Burn image to SD card
  shell:
    cmd: xzcat ./Downloads/{{ download[arch].image }} | dd bs=4m of={{ sd_card_disk.stdout | replace('/dev/disk', '/dev/rdisk') }} conv=sync
    warn: False
  become: yes

- name: Mount SD card partitions
  shell: "diskutil mountDisk {{ sd_card_disk.stdout }}"
  become: yes
