---
- name: Check for mounted boot disk
  shell: "lsblk -o PATH,MOUNTPOINT | grep /media/pi/boot| cut -f1 -d' '"
  register: boot_disk
  changed_when: False

- name: Check for mounted root disk
  shell: "lsblk -o PATH,MOUNTPOINT | grep /media/pi/rootfs | cut -f1 -d' '"
  register: root_disk
  changed_when: False

- name: Unmount boot
  ansible.posix.mount:
    path: /media/pi/boot
    state: unmounted
  become: yes

- name: Unmount root
  ansible.posix.mount:
    path: /media/pi/rootfs
    state: unmounted
  become: yes

- name: "Create Downloads"
  file:
    path: ./Downloads
    state: directory
    mode: 0755

- name: "Download image {{ download[arch].url }}/{{ download[arch].image }}"
  get_url:
    url: "{{ download[arch].url }}/{{ download[arch].image }}"
    dest: "./Downloads/{{ download[arch].image }}"

- name: Burn it
  shell:
    cmd: xzcat ./Downloads/{{ download[arch].image }} | dd bs=4M of=/dev/sdb conv=fsync status=progress
  become: yes

- name: Mount boot
  ansible.posix.mount:
    path: /media/pi/boot
    src: /dev/sdb1
    fstype: vfat
    state: mounted
  become: yes

- name: Mount root
  ansible.posix.mount:
    path: /media/pi/rootfs
    src: /dev/sdb2
    fstype: ext4
    state: mounted
  become: yes
