---
- name: check kubectl get componentstatuses
  command: kubectl get componentstatuses
  register: component_status
  changed_when: False
  failed_when: False

- block:
  - name: kubeadm init
    command: kubeadm init --pod-network-cidr=10.244.0.0/16
    become: yes
    register: kubeadm_init

  - block:
    - set_fact:
        join_command: "{{kubeadm_init.stdout | regex_replace('.*(kubeadm join.*)','\\1') | regex_replace('\\\\n', '') | regex_replace('\\\\\\\\ ', '') | regex_replace('  *', ' ') }}"

    - name: Save join command to vars file
      delegate_to: localhost
      copy:
        content: "---\njoin_command: {{join_command}}\n"
        dest: '{{join_file}}'
    - name: Encrypt join file
      delegate_to: localhost
      shell: ansible-vault encrypt '{{join_file}}'
    when: kubeadm_init is changed
  when: component_status.rc == 1
