---
- name: Check for deployemnt
  command: kubectl get deploy --namespace monitoring prometheus-operator
  failed_when: False
  changed_when: False
  register: deployment

- name: Add deployment
  command: kubectl apply -f nginx-ingress.yaml
  when: deployment.rc != 0
