---
- name: Check for deployemnt
  command: kubectl get deploy --namespace monitoring prometheus-operator
  failed_when: False
  changed_when: False
  register: deployment

- name: Add deployment
  block:
  - name: Clone repo
    command: deploy-monitoring.sh
  when: deployment.rc != 0
