---
- name: Check for deployemnt
  command: kubectl get deploy --namespace monitoring prometheus-operator
  failed_when: False
  changed_when: False
  register: deployment

- name: git clone cluster-monitoring
  git:
    name: git@github.com:TerryHowe/cluster-monitoring.git
    dest: "{{ lookup('env', 'HOME') }}/cluster-monitoring"
    clone: yes
  register: git_carlos

- name: Start the deployment
  block:
    - name: Make suffix
      command: make change_suffix suffix="{{ groups.k8sprimary[0] }}.nip.io"
      args:
        chdir: "{{ lookup('env', 'HOME') }}/cluster-monitoring"

    - name: Make it
      command: make deploy
      args:
        chdir: "{{ lookup('env', 'HOME') }}/cluster-monitoring"
  when: deployment.rc != 0 or git_carlos.changed
