---
- name: Creates kubernetes config directory
  file:
    path: /home/pi/.kube
    owner: pi
    group: pi
    mode: 0755
    state: directory

- name: Check admin.conf
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf

- name: admin.conf exists
  block:
    - name: Check kube config
      command: diff /etc/kubernetes/admin.conf /home/pi/.kube/config
      register: kube_config
      become: yes
      changed_when: False
      failed_when: False

    - name: Copy over the kube config
      command: cp /etc/kubernetes/admin.conf /home/pi/.kube/config
      become: yes
      when: kube_config != 0
  when: admin_conf.stat.exists

- name: admin.conf does not exist
  block:
    - name: Check kube config
      command: diff /etc/kubernetes/kubelet.conf /home/pi/.kube/config
      register: kube_config
      become: yes
      changed_when: False
      failed_when: False

    - name: Copy over the kube config
      command: cp /etc/kubernetes/kubelet.conf /home/pi/.kube/config
      become: yes
      when: kube_config != 0
  when: admin_conf.stat.exists == False

- name: Set kube config permissions
  file:
    path: /home/pi/.kube/config
    owner: pi
    group: pi
    mode: 0600
  become: yes
